# chaos version, used in pattern with manual changes

[icons]
icons = "awesome6"

[[block]]
block = "net"
device = "eno1"
interval = 10

[[block]]
block = "net"
device = "wlp2s0"
interval = 10

[[block]]
block = "sound"
driver = "alsa"

[[block]]
block = "temperature"
chip = "*-isa-*"

[[block]]
block = "memory"
format = "$icon $mem_used/$mem_total ($mem_used_percents)"

[[block]]
block = "cpu"
format = "$barchart $utilization"

[[block]]
block = "battery"
format = "$percentage $time"

[[block]]
block = "time"
interval = 1
format = "$icon $timestamp.datetime(f:'%d-%m-%Y %H:%M:%S')"
