#!/usr/bin/bash

# Setup simple links to shared rc files

# Profile and bashrc
cat >> ~/.profile <<EOF
# Generated by fg-config
[ -f ~/.bashrc ] && source ~/.bashrc
EOF

cat >> ~/.bashrc <<EOF
# Generated by fg-config
[ -f ~/system/rc/bashrc ] && source ~/system/rc/bashrc
EOF

# Vimrc
cat >> ~/.vimrc <<EOF
" Generated by fg-config
source ~/system/rc/vimrc
EOF

