#
# ~/.bashrc
#

# .fgconfig is a symlink to the rc/ dir.
source ~/.fgconfig/bashrc

# Autostart X
if [ -z "$DISPLAY" ] && [ -n "$XDG_VTNR" ] && [ "$XDG_VTNR" -eq 1 ] && ! pgrep X; then
	exec startx
fi
