theme = "native"
icons = "awesome5"


[[block]]
block = "net"
device = "eno1"
format = "{ip}"
interval = 10

[[block]]
block = "net"
device = "wlp2s0"
format = "{ip}"
interval = 10

[[block]]
block = "sound"
driver = "alsa"

[[block]]
block = "temperature"
collapsed = false
chip = "*-isa-*"

[[block]]
block = "memory"
format_mem = "{Mug}/{MTg}GiB ({Mup}%)"

# Never show swap as we do not have any
display_type = "memory"
clickable = false

[[block]]
block = "cpu"
format = "{barchart} {utilization}"

[[block]]
block = "battery"
format = "{percentage}% {time}"

[[block]]
block = "time"
interval = 1
format = "%d-%m-%Y %H:%M:%S"
