" Get user vimrc
source ~/system/git/rc/vimrc

" Auto doxygen syntax coloring
let g:load_doxygen_syntax=1

" Clang format
let g:clang_format#detect_style_file = 1
let g:clang_format#auto_formatexpr = 1
autocmd FileType c,cpp,objc map <buffer><F2> :ClangFormat<CR>
autocmd FileType c,cpp,objc imap <buffer><silent><F2> <Esc>:ClangFormat<CR>i

" Rust
let g:rustfmt_autosave = 1
let g:rustfmt_fail_silently = 0

" Use Indentline with utf8 bar
let g:indentLine_char = '│'

" Add locally configured plugins
execute pathogen#infect ()
