#!/bin/bash
#
# ~/.xinitrc
#
# Executed by startx (run your window manager from here)

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
	for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
		[ -x "$f" ] && . "$f"
	done
	unset f
fi

####### Basic ########

# Monitors.
# HDMI limits to 144Hz. DP1 is valve index. DP5 is MST clone.
sleep 2s
xrandr \
	--output DisplayPort-0 --primary --mode 2560x1440 --rate 165 --pos 1440x560 \
	--output HDMI-A-0 --mode 2560x1440 --rotate left --pos 0x0 \
	--output DisplayPort-1 --off

# Disable bell
xset -b

# Cursor
[[ -f ~/.Xressources ]] && xrdb -merge ~/.Xressources

######## Desktop #########

export QT_QPA_PLATFORMTHEME="qt6ct"

# Launch autostart stuff
#dex -a

# i3 Window Manager. Push logs to systemd journal
exec systemd-cat --identifier=i3 i3
