#!/bin/bash
#
# ~/.xinitrc
#
# Executed by startx (run your window manager from here)

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
	for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
		[ -x "$f" ] && . "$f"
	done
	unset f
fi

####### Basic ########

# Disable bell
xset -b

# Cursor
[[ -f ~/.Xressources ]] && xrdb -merge ~/.Xressources

######## Desktop #########

# Kde theme and terminal
export TERMINAL=konsole
export QT_QPA_PLATFORMTHEME="qt5ct"

# Launch autostart stuff
dex -a

~/.config/slam/slam &

(
	# Wait for slam to finish. Not pretty...
	sleep 3s;
	# Set a random cat picture as background
	# Will one day be replaced by slam (if I improve it...)
	feh --no-fehbg --image-bg black --bg-max --randomize $HOME/user/cats/
) &

# i3 Window Manager
exec i3 &> ~/.i3/log
